#!/usr/bin/env bash
set -e
set -o pipefail
url=$(zenity --text="URL to download" --title="Input URL" --entry 2>/dev/null)
mkdir -p ~/Videos && cd ~/Videos && youtube-dl "${url}" | zenity --progress --pulsate --auto-close --auto-kill 2>/dev/null
xdg-open "$(ls ~/Videos -tr |  head -n1)"

